name: Trigger auto deployment for hollowmere-web

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/hollowmere-web-AutoDeployTrigger-04dce7cb-4c3f-459b-ad77-c20e5a83ac38.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.HOLLOWMEREWEB_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.HOLLOWMEREWEB_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.HOLLOWMEREWEB_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: hollowmerennt.azurecr.io
          registryUsername: ${{ secrets.HOLLOWMEREWEB_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.HOLLOWMEREWEB_REGISTRY_PASSWORD }}
          containerAppName: hollowmere-web
          resourceGroup: hollowmere-prod-rg
          imageToBuild: hollowmerennt.azurecr.io/hollowmere-web:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


